- modules/app-main/src/main/resources/assets/js/home/launcher.js
- modules/app-main/src/main/resources/assets/js/home/main.js
Added launcher reload in apps and home with `ApplicationEvent` listeners.
> Refresh Launcher panel when the list of tools changes #5571

- modules/app-applications/src/main/resources/assets/js/app/browse/ApplicationBrowsePanel.ts
Fixed path for the moved image.
> lib-admin-ui: Remove unused image files in lib-admin-ui #4

- modules/app-contentstudio/src/main/resources/admin/tools/main/main.html
-Required configuration so CKEditor can be used on html page
> Add integration with CKEditor (Content Wizard) #53

- modules/app-contentstudio/src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
- modules/app-contentstudio/src/main/resources/assets/js/app/view/MobileContentItemStatisticsPanel.ts
- modules/app-contentstudio/src/main/resources/assets/js/app/view/detail/NonMobileDetailsPanelsManager.ts
- also fixed the floating context window showing after resizing from mobile mode
- and fixed context window would not go from floating to docked after mobile mode
> Content grid is losing selection after detail panel expands #49

- modules/app-contentstudio/src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateSelector.ts
Restored missing deferred resolve call.
> Site Inspection Panel - Page Template selector is empty #91

- modules/app-main/src/main/resources/admin/tools/home/home.html
- modules/app-standardidprovider/src/main/resources/idprovider/idprovider.html
-IE11 does not support Node.remove() method, only Node.removeChild()
> IE11: No background image on login page #113

- testing/app-users/libs/app_const.js
- testing/app-users/page_objects/browsepanel/group.statistics.panel.js
- testing/app-users/page_objects/page.js
- testing/app-users/page_objects/wizardpanel/group.wizard.js
- testing/app-users/page_objects/wizardpanel/role.wizard.js
- testing/app-users/page_objects/wizardpanel/user.wizard.js
- testing/app-users/tests/group.save.statistics.spec.js
- testing/app-users/tests/role.wizard.spec.js
Tests for group : saving, editing and displaying on the statistics panel
> xp-apps#121 Implement js-ui-tests for saving of a group

- modules/app-users/src/main/resources/lib/roles.js
> Replace node layer with `lib-auth` calls for `createRole` #82

- modules/app-users/src/main/resources/lib/roles.js
> Lib Auth - Modify role #145

- .travis.yml
- build.gradle
Fixed unresolved `includedBuild` dependency when running on CI.
> Fix build running CI

- modules/app-contentstudio/src/main/resources/admin/i18n/phrases.properties
- modules/app-contentstudio/src/main/resources/admin/i18n/phrases_ru.properties
- modules/app-contentstudio/src/main/resources/assets/js/app/move/MoveContentDialog.ts
* Added processing message above the progress bar.
* Added controls lock, when the move dialog is still processing, but progress bar not displayed yet.
> Show progress bar while the content is being moved #221

- .gitignore
- testing/README.md
- testing/app-users/build.gradle
- testing/app-users/package-lock.json
Refactored `testing/app-users` build file.
Added Zip tasks to archive results after the server is stopped.
Renamed main test tasks into `testApp` and `testAppLocally`.
> Add zip task to testing Gradle config

- modules/app-contentstudio/src/main/resources/assets/js/app/issue/view/IssueDialog.ts
Updated wrong config, passed to the parent constructor.
> Fix absent title in the issue dialogs

- modules/app-users/src/main/resources/assets/js/app/wizard/GroupWizardPanel.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/RoleWizardPanel.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/UserItemWizardPanel.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/UserStoreWizardPanel.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/UserWizardPanel.ts
- modules/app-users/src/main/resources/lib/common.js
- modules/app-users/src/main/resources/lib/groups.js
- modules/app-users/src/main/resources/lib/roles.js
- modules/app-users/src/main/resources/lib/users.js
- modules/app-users/src/main/resources/lib/userstores.js
Updated wizard header inputs: they will be normalized, before retrieving values from them, except the `isNew()` check.
> Users App - trim spaces in displayName input (Wizards) #184

- modules/app-users/src/main/resources/admin/i18n/phrases.properties
- modules/app-users/src/main/resources/admin/i18n/phrases_es.properties
- modules/app-users/src/main/resources/admin/i18n/phrases_fr.properties
- modules/app-users/src/main/resources/admin/i18n/phrases_no.properties
- modules/app-users/src/main/resources/admin/i18n/phrases_pt.properties
- modules/app-users/src/main/resources/admin/i18n/phrases_ru.properties
- modules/app-users/src/main/resources/admin/i18n/phrases_sv.properties
- modules/app-users/src/main/resources/assets/js/app/wizard/ChangeUserPasswordDialog.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/GroupWizardPanel.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/RoleWizardPanel.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/UserEmailWizardStepForm.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/UserItemWizardPanel.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/UserPasswordWizardStepForm.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/UserStoreWizardPanel.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/UserWizardPanel.ts
- modules/app-users/src/main/resources/lib/common.js
- modules/app-users/src/main/resources/lib/groups.js
- modules/app-users/src/main/resources/lib/roles.js
- modules/app-users/src/main/resources/lib/users.js
- modules/app-users/src/main/resources/lib/userstores.js
Added validation by symbols to the password generator and wizard step.
Added removal of the whitespaces from the password in case client-side validation will fail.
> UserWizard - trim spaces in a password field #173

- modules/app-contentstudio/src/main/resources/assets/js/app/issue/view/IssueListDialog.ts
- removed automatic tab switching as discussed with @alansemenov
> IssueListDialog - 'Open' tab should open when an issue was opened #412

- testing/app-applications/libs/app_const.js
- testing/app-applications/page_objects/applications/application.item.statistic.panel.js
- testing/app-applications/page_objects/applications/applications.browse.panel.js
- testing/app-applications/page_objects/page.js
- testing/app-applications/specs/app.item.statistics.spec.js
- testing/app-applications/specs/login.page.spec.js
**Tests:**
* Added tests for the `ItemStatisticsPanel` for stopped and running applications.
* Implemented `ItemStatisticsPanel` test utilities in the `application.item.statistic.panel.js`.
**Fixes:**
* `applications.browse.panel.js` -- fixed Start/Stop buttons, optimized XPath, added several new functions.
* Added several methods for the `Page` object in the `page.js`.
_**Please, squash the PR when merging.**_
> Tests for Item Statistics Panel

- modules/app-contentstudio/src/main/resources/assets/js/app/wizard/action/SaveAsTemplateAction.ts
- modules/app-contentstudio/src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
…button pressed in a content wizard #453
> Error when trying to save as template from a non-site content

- modules/app-users/build.gradle
- modules/app-users/src/main/java/com/enonic/xp/app/users/lib/auth/CreateUserStoreHandler.java
- modules/app-users/src/main/java/com/enonic/xp/app/users/lib/auth/ScriptValueToAuthConfigTranslator.java
- modules/app-users/src/main/resources/assets/js/api/graphql/userStore/CreateUserStoreRequest.ts
- modules/app-users/src/main/resources/assets/js/api/graphql/userStore/GetUserStoreByKeyRequest.ts
- modules/app-users/src/main/resources/assets/js/app/wizard/UserStoreWizardPanel.ts
- modules/app-users/src/main/resources/lib/auth.js
- modules/app-users/src/main/resources/lib/userstores.js
- modules/app-users/src/main/resources/services/graphql/types/inputs.js
- modules/app-users/src/main/resources/site/test/createUserStore-test.js
- modules/app-users/src/main/resources/site/test/getPermissions-test.js
- modules/app-users/src/main/resources/site/test/getUserStore-test.js
- modules/app-users/src/test/java/com/enonic/xp/app/users/lib/auth/CreateUserStoreHandlerTest.java
- modules/app-users/src/test/java/com/enonic/xp/app/users/lib/auth/GetPermissionsHandlerTest.java
- modules/app-users/src/test/java/com/enonic/xp/app/users/lib/auth/GetUserStoreHandlerTest.java
- modules/app-users/src/test/java/com/enonic/xp/app/users/lib/auth/TestDataFixtures.java
Added `auth.js` `createUserStore` implementation.
Added AuthConfig translator.
Added tests for old and new handlers.
> Users App - GraphQL - Create user store #462

- modules/app-users/src/main/resources/lib/principals.js
Merge https://github.com/enonic/xp/pull/6035 first
> Users app - Use authLib.deletePrincipal function (#560)

- modules/app-applications/src/main/resources/i18n/phrases_pl.properties
- modules/app-contentstudio/src/main/resources/i18n/phrases_pl.properties
- modules/app-standardidprovider/src/main/resources/i18n/phrases_pl.properties
- modules/app-users/src/main/resources/i18n/phrases_pl.properties
> Translate XP Apps to Polish

- modules/app-contentstudio/src/main/resources/assets/js/app/publish/ContentUnpublishDialog.ts
> Unpublish dialog - Text in subheader is not updated after previous operation

- testing/app-contentstudio/libs/app_const.js
- testing/app-contentstudio/libs/content.builder.js
- testing/app-contentstudio/libs/studio.utils.js
- testing/app-contentstudio/page_objects/wizardpanel/content.wizard.panel.js
- testing/app-contentstudio/page_objects/wizardpanel/liveform/page.components.view.js
- testing/app-contentstudio/specs/page-editor/fragment.save.detach.spec.js
- testing/app-users/page_objects/wizardpanel/userstore.wizard.js
- testing/app-users/tests/userstore.save.before.close.dialog.spec.js
- testing/app-users/tests/userstore.wizard.spec.js
> Add ui-tests for 'Detach from Fragment' menu item #546
